Locales['bg'] = {
    -- Cloakroom
    ['cloakroom'] = 'Съблекалня',
    ['ems_clothes_civil'] = 'Цивилни дрехи',
    ['ems_clothes_ems'] = 'Лекарска униформа',
    -- Vehicles
    ['ambulance'] = 'Лиенйка',
    ['helicopter_prompt'] = 'Натисни ~INPUT_CONTEXT~ за да получиш достъп до ~y~опции за хеликоптер~s~.',
    ['garage_prompt'] = 'Натисни ~INPUT_CONTEXT~ за да получиш достъп до ~y~опции за линейки~s~.',
    ['garage_title'] = 'Опции за автомобили',
    ['garage_stored'] = 'Линейката беше прибрана',
    ['garage_notstored'] = 'Линейката беше прибрана в гаража',
    ['garage_storing'] = 'we\'re опитваме се да приберем линейката сигурни ли сте ч около вас няма хора.',
    ['garage_has_stored'] = 'Линейката беше прибрана в гаража',
    ['garage_has_notstored'] = 'Не беше намерена линейка в близост която е на ваше име',
    ['garage_notavailable'] = 'Вашата линейка не е в гаража проверете в наказателния паркинг.',
    ['garage_blocked'] = 'there\'s няма свободни места за изкарване!',
    ['garage_empty'] = 'Ти нямаш линейка в гаража.',
    ['garage_released'] = 'Ваашата линейка беше прибрана .',
    ['garage_store_nearby'] = 'Няма линейки наблизо.',
    ['garage_storeditem'] = 'Отвори гаража',
    ['garage_storeitem'] = 'Линейката беше прибрана в гаража',
    ['garage_buyitem'] = 'Магазин за линейки',
    ['shop_item'] = '$%s',
    ['vehicleshop_title'] = 'Магазин за линейки',
    ['vehicleshop_confirm'] = 'Сигурни ли сте че искате да закупите линейката?',
    ['vehicleshop_bought'] = 'Вие закупихте ~y~%s~s~ за ~g~$%s~s~',
    ['vehicleshop_money'] = 'Не можете да си закупите линейката отидете до банката и изтеглете пари',
    ['vehicleshop_awaiting_model'] = 'Линейката вмомента се кара към болницата ~g~товари и се кара~s~ моля изчакайте',
    ['confirm_no'] = 'Не',
    ['confirm_yes'] = 'Да',
    -- Action Menu
    ['revive_inprogress'] = 'Помгате му!',
    ['revive_complete'] = 'Вие помогнахте на ~y~%s~s~',
    ['revive_complete_award'] = 'Вие помогнахте на ~y~%s~s~ и изкарахте ~g~$%s~s~!',
    ['revive_fail_offline'] = 'Този гражданин вече не в града',
    ['heal_inprogress'] = 'Вмомента превързвате!',
    ['heal_complete'] = 'Упсешно превързахте ~y~%s~s~',
    ['no_players'] = 'Няма граждани наблизо',
    ['player_not_unconscious'] = 'Този гражданин не в безсъзнание!',
    ['player_not_conscious'] = 'Този гражданин е в безсъзнание!',
    -- Boss Menu
    ['boss_actions'] = 'Шефско меню',
    -- Misc
    ['invalid_amount'] = '~r~Невалидна сума',
    ['actions_prompt'] = 'Натиснете ~INPUT_CONTEXT~ за да получите достъп до ~y~Опциите за болницата~s~.',
    ['deposit_amount'] = 'Депозирай сума',
    ['money_withdraw'] = 'Изтегли сума',
    ['fast_travel'] = 'Натисни ~INPUT_CONTEXT~ за да отидеш бързо до там.',
    ['open_pharmacy'] = 'Натисни ~INPUT_CONTEXT~ за да отвориш аптеката.',
    ['pharmacy_menu_title'] = 'Аптека',
    ['pharmacy_take'] = 'Вземи <span style="color:blue;">%s</span>',
    ['medikit'] = 'Аптечка',
    ['bandage'] = 'Бандаж',
    ['max_item'] = 'Вече имаш достатъчен брой.',
    -- F6 Menu
    ['ems_menu'] = 'Лекарско меню',
    ['ems_menu_title'] = 'Болница - Лекарско меню',
    ['ems_menu_revive'] = 'Помагате на човек',
    ['ems_menu_putincar'] = 'Вкарайте в автомобила',
    ['ems_menu_small'] = 'Помага за малки рани',
    ['ems_menu_big'] = 'Лекува големи рани',
    -- Phone
    ['alert_ambulance'] = 'Блолница',
    -- Death
    ['respawn_available_in'] = 'Възможно съживяване след ~b~%s минути и %s секунди~s~',
    ['respawn_bleedout_in'] = 'Ще изкървищ след ~b~%s минути и %s секунди~s~\n',
    ['respawn_bleedout_prompt'] = 'Задръж [~b~E~s~] за да се съживиш',
    ['respawn_bleedout_fine'] = 'Задръж [~b~E~s~] за да се съживиш за ~g~$%s~s~',
    ['respawn_bleedout_fine_msg'] = 'Ти плати ~r~$%s~s~ за да се съживиш.',
    ['distress_send'] = 'Натисни [~b~G~s~] за да изпратиш сигнал към медиците',
    ['distress_sent'] = 'Сигнал беще изпратен към медиците които са на смяна!',
    ['combatlog_message'] = 'Вие бяхте автоматично съжиевен you\'ve преди сте излезнали от града докато сте били в безсъзнание.',
    -- Revive
    ['revive_help'] = 'Помогнете на гражданина',
    -- Item
    ['used_medikit'] = 'Ти използва една ~y~1x~s~ аптечка',
    ['used_bandage'] = 'Ти използва ~y~1x~s~ бандаж',
    ['not_enough_medikit'] = 'Ти нямаш ~b~аптечка~s~.',
    ['not_enough_bandage'] = 'Ти нямаш ~b~бандаж~s~.',
    ['healed'] = 'Лекарите ви залепиха няколко лепенки и ви помогнаха.',
    -- Blips
    ['blip_hospital'] = 'Болница',
    ['blip_dead'] = 'Гражданин в безсъзнание',
  }
  